# Generated by Django 4.2.5 on 2023-09-28 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='имя заказчика')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Камень',
                'verbose_name_plural': 'Камни',
            },
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='deals.customer'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='deals.gem'),
        ),
    ]
